### ISSUE TITLE
请问有没有国内可用镜像？

### ISSUE THREAD

**Issue by kknd222** [flyfox666/mcpo_docker_use#1]
不知为何，国内拉不到你这个镜像
flyfox666/mcpo_docker_use
换了好多加速类似docker.zhai.cm/flyfox666/mcpo_docker_use

**Comment by flyfox666** [comment]
昨天刚刚放上去呀，要么用dockerhub 看看，我自己用可以的

ghcr.io/flyfox666/mcpo_docker_use 
# or 

flyfox666bbw/mcpo_docker_use from dockerhub

**Comment by flyfox666** [comment]
> 不知为何，国内拉不到你这个镜像 flyfox666/mcpo_docker_use 换了好多加速类似docker.zhai.cm/flyfox666/mcpo_docker_use

直接下载dockerfile make也方便啊

**Comment by kknd222** [comment]
最终在虚拟机里，外边windows全局挂T跑下来了
但是启动后，openwebui验证报network problem
我的compose 配置是
```
version: "3.3"
services:
  mcpo_docker_use:
    container_name: mcpo
    restart: unless-stopped
    ports:
      - 8000:8000
    volumes:
      - ./config.json:/app/config/config.json
      - ./logs:/app/logs
    environment:
      - MCPO_API_KEY=xxx
    healthcheck:
      test: curl -f http://localhost:8000/docs
      interval: 30s
      timeout: 10s
      retries: "3"
      start_period: 40s
    image: ghcr.io/flyfox666/mcpo_docker_use:latest
networks: {}

```
config配置是

```
{
  "mcpServers": {
    "fetch": {
      "command": "npx",
      "args": ["-y", "@wopal/mcp-server-hotnews"]
    }  
  }
}
```
openwebui密钥配置就是xxx，http://IP:8000/fetch
打开http://IP:8000/fetch/docs#/ 是swagger，根据swagger调用
```
curl -X 'POST' \
  'http://IP:8000/fetch/get_hot_news' \
  -H 'accept: application/json' \
  -H 'Authorization: Bearer xxx' \
  -H 'Content-Type: application/json' \
  -d '{
  "sources": [
    "string",2
  ]
}'
```
也能正常返回
